language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - nightly
env:
  matrix:
    - GROUP=docs
    - GROUP=nbextensions
    - GROUP=python
addons:
  apt:
    packages:
    - pandoc
    - enchant
before_install:
  - pip install -U pip wheel setuptools
  - pip install invoke
install:
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-14.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-14.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-14.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
  - invoke install --group="$GROUP"
script:
  - invoke tests --group="$GROUP"
after_success:
  - invoke after_success --group="$GROUP"
