language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - nightly
env:
  global:
    - MOZ_HEADLESS=1
  matrix:
    - GROUP=docs
    - GROUP=nbextensions
    - GROUP=python
addons:
  apt:
    packages:
    - pandoc
  firefox: latest
before_install:
  - pip install -U pip wheel setuptools
  - pip install invoke
install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - invoke install --group="$GROUP"
script:
  - invoke tests --group="$GROUP"
after_success:
  - invoke aftersuccess --group="$GROUP"
