language: python
python:
  - 2.7
  - 3.4
env:
  matrix:
    - GROUP=js
    - GROUP=
  global:
    - secure: P1srvJIQ+vFCd7jTuxqhp07JF+wqWtWkCYDcrT8hHZMgsy0wjNTkXP3h5+7dboYOjhmJcy2GX3tsdIzmcSm6/NttMqHhK1WL+dCgFgLijsyUzyOEsAxGi/E4w9xxX5WRRQdFniOgNVpv9bzrD0ngpUCXdQnutc+52mCDAS+hYMk=
before_install:
  # Pierre Carrier's PPA for PhantomJS and CasperJS
  - time sudo add-apt-repository -y ppa:pcarrier/ppa
  - sudo apt-get update
  - git clone --recursive https://github.com/ipython/ipython.git
install:
  - sudo apt-get install pandoc casperjs libzmq3-dev
  # pin tornado < 4 for js tests while phantom is on super old webkit
  - if [[ $GROUP == 'js' ]]; then pip install 'tornado<4'; fi
  - cd ipython && git submodule update && pip install -e ".[notebook]" && cd ..
  - pip install -r requirements.txt
  - pip install nose requests!=2.4.2 fabric
  - python setup.py install
  - if [[ $GROUP == 'js' ]]; then cp nbextensions/* $(ipython locate)/nbextensions/; fi
script:
  - ./scripts/runtests $GROUP
after_success:
  - if [[ $GROUP != 'js' ]]; then fab travis_docs; fi
