dist: xenial
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - nightly
env:
  global:
    - MOZ_HEADLESS=1
  matrix:
    - GROUP=docs
    - GROUP=nbextensions
    - GROUP=python
matrix:
  exclude:
  - python: 2.7
    env: GROUP=docs
  - python: 3.5
    env: GROUP=docs
  - python: 3.6
    env: GROUP=docs
  - python: nightly
    env: GROUP=docs
addons:
  apt:
    packages:
    - pandoc
  firefox: latest
before_install:
  - pip install -U pip wheel setuptools
install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - python tasks.py install --group="$GROUP"
script:
  - python tasks.py tests --group="$GROUP"
after_success:
  - python tasks.py aftersuccess --group="$GROUP"
